//
//  Ability.swift
//  TG
//
//  Created by Andrii Narinian on 8/7/17.
//  Copyright © 2017 ROLIQUE. All rights reserved.
//

import Foundation

var abilityList = Set<String>() {
    didSet {
        print("abilityList: \(abilityList.sorted(by: { $0 < $1 }))")
    }
}

class Ability: Model {
    
    required init(dict: [String: Any?]) {
        super.init(dict: dict)
        self.type = "Ability"
        self.id = dict["id"] as? String
        self.url = dict["url"] as? String
        self.name = dict["name"] as? String
    }
    
    required init(id: String, type: ModelType) {
        super.init(id: id, type: type)
    }
    
    override var encoded: [String : Any?] {
        let dict: [String: Any?] = [
            "id": id,
            "name": name,
            "url": url,
            "type": type
        ]
        return dict
    }
}

enum AbilityType: String {
    case
    Unset = "<Unset>",
    AbilityB_Bounce = "AbilityB_Bounce",
    AbilityCLeapOff = "AbilityCLeapOff",
    Ability_Dash = "Ability_Dash",
    Ability_Grumpjaw_Eat = "Ability_Grumpjaw_Eat",
    Ability_Leap = "Ability_Leap",
    Ability_SelfDestruct = "Ability_SelfDestruct",
    Ability__B_Bounce = "Ability__B_Bounce",
    Ability__B_EndingAttack = "Ability__B_EndingAttack",
    Ability__Idris__A_Blink = "Ability__Idris__A_Blink",
    Ability__Idris__A_Dash = "Ability__Idris__A_Dash",
    Ability__Vox__DashAndFire__AnimateAndFire = "Ability__Vox__DashAndFire__AnimateAndFire",
    Ability__Vox__DashAndFire__Dash = "Ability__Vox__DashAndFire__Dash",
    Ability__Vox__DashToLocation = "Ability__Vox__DashToLocation",
    Aegis = "Aegis",
    AtlasPauldron = "Atlas Pauldron",
    C_SpitOut = "C_SpitOut",
    CandyKissy = "Candy - Kissy",
    CandyTaunt = "Candy - Taunt",
    CandyVOTaunt = "Candy - VO Taunt",
    Contraption = "Contraption",
    Crucible = "Crucible",
    CrystalInfusion = "Crystal Infusion",
    Echo = "Echo",
    Emote_Taunt = "Emote_Taunt",
    Flare = "Flare",
    Flaregun = "Flaregun",
    FountainofRenewal = "Fountain of Renewal",
    HERO_ABILITY_ADAGIO_FORTUNES_SMILE_NAME = "HERO_ABILITY_ADAGIO_FORTUNES_SMILE_NAME",
    HERO_ABILITY_ADAGIO_FRIENDSHIP_NAME = "HERO_ABILITY_ADAGIO_FRIENDSHIP_NAME",
    HERO_ABILITY_ADAGIO_GASOLINE_SOAKED_NAME = "HERO_ABILITY_ADAGIO_GASOLINE_SOAKED_NAME",
    HERO_ABILITY_ALPHA_A_NAME = "HERO_ABILITY_ALPHA_A_NAME",
    HERO_ABILITY_ALPHA_B_NAME = "HERO_ABILITY_ALPHA_B_NAME",
    HERO_ABILITY_ALPHA_C_NAME = "HERO_ABILITY_ALPHA_C_NAME",
    HERO_ABILITY_ARDAN_A = "HERO_ABILITY_ARDAN_A",
    HERO_ABILITY_ARDAN_B = "HERO_ABILITY_ARDAN_B",
    HERO_ABILITY_ARDAN_C = "HERO_ABILITY_ARDAN_C",
    HERO_ABILITY_BARON_A_NAME = "HERO_ABILITY_BARON_A_NAME",
    HERO_ABILITY_BARON_B_NAME = "HERO_ABILITY_BARON_B_NAME",
    HERO_ABILITY_BARON_C_NAME = "HERO_ABILITY_BARON_C_NAME",
    HERO_ABILITY_CATHERINE_ARCANE_SHIELD_NAME = "HERO_ABILITY_CATHERINE_ARCANE_SHIELD_NAME",
    HERO_ABILITY_CATHERINE_ASSASSINS_CHARGE_NAME = "HERO_ABILITY_CATHERINE_ASSASSINS_CHARGE_NAME",
    HERO_ABILITY_CATHERINE_DEADLY_GRACE_NAME = "HERO_ABILITY_CATHERINE_DEADLY_GRACE_NAME",
    HERO_ABILITY_CELESTE_A_NAME = "HERO_ABILITY_CELESTE_A_NAME",
    HERO_ABILITY_CELESTE_B_NAME = "HERO_ABILITY_CELESTE_B_NAME",
    HERO_ABILITY_CELESTE_C_NAME = "HERO_ABILITY_CELESTE_C_NAME",
    HERO_ABILITY_FORTRESS_A_NAME = "HERO_ABILITY_FORTRESS_A_NAME",
    HERO_ABILITY_FORTRESS_B_NAME = "HERO_ABILITY_FORTRESS_B_NAME",
    HERO_ABILITY_FORTRESS_C_NAME = "HERO_ABILITY_FORTRESS_C_NAME",
    HERO_ABILITY_GLAIVE_AFTERBURN_NAME = "HERO_ABILITY_GLAIVE_AFTERBURN_NAME",
    HERO_ABILITY_GLAIVE_BLOODSONG_NAME = "HERO_ABILITY_GLAIVE_BLOODSONG_NAME",
    HERO_ABILITY_GLAIVE_TWISTED_STROKE_NAME = "HERO_ABILITY_GLAIVE_TWISTED_STROKE_NAME",
    HERO_ABILITY_GRUMPJAW_A_NAME = "HERO_ABILITY_GRUMPJAW_A_NAME",
    HERO_ABILITY_GRUMPJAW_B_NAME = "HERO_ABILITY_GRUMPJAW_B_NAME",
    HERO_ABILITY_GRUMPJAW_C_NAME = "HERO_ABILITY_GRUMPJAW_C_NAME",
    HERO_ABILITY_GWEN_A_NAME = "HERO_ABILITY_GWEN_A_NAME",
    HERO_ABILITY_GWEN_B_NAME = "HERO_ABILITY_GWEN_B_NAME",
    HERO_ABILITY_GWEN_C_NAME = "HERO_ABILITY_GWEN_C_NAME",
    HERO_ABILITY_HERO009_BURNING_WOUNDS_NAME = "HERO_ABILITY_HERO009_BURNING_WOUNDS_NAME",
    HERO_ABILITY_HERO009_LIFE_FROM_PAIN_NAME = "HERO_ABILITY_HERO009_LIFE_FROM_PAIN_NAME",
    HERO_ABILITY_HERO009_SHIMMERHEART_NAME = "HERO_ABILITY_HERO009_SHIMMERHEART_NAME",
    HERO_ABILITY_HERO021_A_NAME = "HERO_ABILITY_HERO021_A_NAME",
    HERO_ABILITY_HERO021_B_NAME = "HERO_ABILITY_HERO021_B_NAME",
    HERO_ABILITY_HERO021_C_NAME = "HERO_ABILITY_HERO021_C_NAME",
    HERO_ABILITY_HERO036_A_NAME = "HERO_ABILITY_HERO036_A_NAME",
    HERO_ABILITY_HERO036_B_NAME = "HERO_ABILITY_HERO036_B_NAME",
    HERO_ABILITY_HERO036_C_NAME = "HERO_ABILITY_HERO036_C_NAME",
    HERO_ABILITY_HERO042_A_NAME = "HERO_ABILITY_HERO042_A_NAME",
    HERO_ABILITY_HERO042_B_NAME = "HERO_ABILITY_HERO042_B_NAME",
    HERO_ABILITY_HERO042_C_NAME = "HERO_ABILITY_HERO042_C_NAME",
    HERO_ABILITY_IDRIS_A_NAME = "HERO_ABILITY_IDRIS_A_NAME",
    HERO_ABILITY_IDRIS_B_NAME = "HERO_ABILITY_IDRIS_B_NAME",
    HERO_ABILITY_IDRIS_C_NAME = "HERO_ABILITY_IDRIS_C_NAME",
    HERO_ABILITY_JOULE_ORBITAL_NUKE = "HERO_ABILITY_JOULE_ORBITAL_NUKE",
    HERO_ABILITY_JOULE_RHAPSODY_CANNONS = "HERO_ABILITY_JOULE_RHAPSODY_CANNONS",
    HERO_ABILITY_JOULE_RHAPSODY_POWERSLIDE = "HERO_ABILITY_JOULE_RHAPSODY_POWERSLIDE",
    HERO_ABILITY_KESTREL_A_NAME = "HERO_ABILITY_KESTREL_A_NAME",
    HERO_ABILITY_KESTREL_B_NAME = "HERO_ABILITY_KESTREL_B_NAME",
    HERO_ABILITY_KESTREL_C_NAME = "HERO_ABILITY_KESTREL_C_NAME",
    HERO_ABILITY_KOSHKA_FRENZY_NAME = "HERO_ABILITY_KOSHKA_FRENZY_NAME",
    HERO_ABILITY_KOSHKA_TWIRL_NAME = "HERO_ABILITY_KOSHKA_TWIRL_NAME",
    HERO_ABILITY_KOSHKA_POUNCE_NAME = "HERO_ABILITY_KOSHKA_POUNCE_NAME",
    HERO_ABILITY_LANCE_A_NAME = "HERO_ABILITY_LANCE_A_NAME",
    HERO_ABILITY_LANCE_B_NAME = "HERO_ABILITY_LANCE_B_NAME",
    HERO_ABILITY_LANCE_C_NAME = "HERO_ABILITY_LANCE_C_NAME",
    HERO_ABILITY_LYRA_A_NAME = "HERO_ABILITY_LYRA_A_NAME",
    HERO_ABILITY_LYRA_B_NAME = "HERO_ABILITY_LYRA_B_NAME",
    HERO_ABILITY_LYRA_C_NAME = "HERO_ABILITY_LYRA_C_NAME",
    HERO_ABILITY_OZO_A_NAME = "HERO_ABILITY_OZO_A_NAME",
    HERO_ABILITY_OZO_B_NAME = "HERO_ABILITY_OZO_B_NAME",
    HERO_ABILITY_OZO_C_NAME = "HERO_ABILITY_OZO_C_NAME",
    HERO_ABILITY_PETAL_BRAMBLETHORN_SEED_NAME = "HERO_ABILITY_PETAL_BRAMBLETHORN_SEED_NAME",
    HERO_ABILITY_PETAL_SHOUT_OF_THE_ENTS_NAME = "HERO_ABILITY_PETAL_SHOUT_OF_THE_ENTS_NAME",
    HERO_ABILITY_PETAL_THORNSTORM_NAME = "HERO_ABILITY_PETAL_THORNSTORM_NAME",
    HERO_ABILITY_PHINN_A_NAME = "HERO_ABILITY_PHINN_A_NAME",
    HERO_ABILITY_PHINN_B_NAME = "HERO_ABILITY_PHINN_B_NAME",
    HERO_ABILITY_PHINN_C_NAME = "HERO_ABILITY_PHINN_C_NAME",
    HERO_ABILITY_REIM_A_NAME = "HERO_ABILITY_REIM_A_NAME",
    HERO_ABILITY_REIM_B_NAME = "HERO_ABILITY_REIM_B_NAME",
    HERO_ABILITY_REIM_C_NAME = "HERO_ABILITY_REIM_C_NAME",
    HERO_ABILITY_REZA_A_NAME = "HERO_ABILITY_REZA_A_NAME",
    HERO_ABILITY_REZA_B_NAME = "HERO_ABILITY_REZA_B_NAME",
    HERO_ABILITY_REZA_C_NAME = "HERO_ABILITY_REZA_C_NAME",
    HERO_ABILITY_RINGO_HELLFIRE_SAKE_NAME = "HERO_ABILITY_RINGO_HELLFIRE_SAKE_NAME",
    HERO_ABILITY_RINGO_TWIRLING_SILVER_NAME = "HERO_ABILITY_RINGO_TWIRLING_SILVER_NAME",
    HERO_ABILITY_RINGO_WING_CUT_NAME = "HERO_ABILITY_RINGO_WING_CUT_NAME",
    HERO_ABILITY_RONA_A_NAME = "HERO_ABILITY_RONA_A_NAME",
    HERO_ABILITY_RONA_B_NAME = "HERO_ABILITY_RONA_B_NAME",
    HERO_ABILITY_RONA_C_NAME = "HERO_ABILITY_RONA_C_NAME",
    HERO_ABILITY_SAMUEL_A_NAME = "HERO_ABILITY_SAMUEL_A_NAME",
    HERO_ABILITY_SAMUEL_B_NAME = "HERO_ABILITY_SAMUEL_B_NAME",
    HERO_ABILITY_SAMUEL_C_NAME = "HERO_ABILITY_SAMUEL_C_NAME",
    HERO_ABILITY_SAW_EXPLOSIVE_TIPPED_SHELLS_NAME = "HERO_ABILITY_SAW_EXPLOSIVE_TIPPED_SHELLS_NAME",
    HERO_ABILITY_SAW_ROADIE_RUN_NAME = "HERO_ABILITY_SAW_ROADIE_RUN_NAME",
    HERO_ABILITY_SAW_SUPPRESSING_FIRE_NAME = "HERO_ABILITY_SAW_SUPPRESSING_FIRE_NAME",
    HERO_ABILITY_SAYOC_A = "HERO_ABILITY_SAYOC_A",
    HERO_ABILITY_SAYOC_B = "HERO_ABILITY_SAYOC_B",
    HERO_ABILITY_SAYOC_C = "HERO_ABILITY_SAYOC_C",
    HERO_ABILITY_SEBA_A_NAME = "HERO_ABILITY_SEBA_A_NAME",
    HERO_ABILITY_SEBA_B_NAME = "HERO_ABILITY_SEBA_B_NAME",
    HERO_ABILITY_SEBA_C_NAME = "HERO_ABILITY_SEBA_C_NAME",
    HERO_ABILITY_SKAARF_A_SPITFIRE = "HERO_ABILITY_SKAARF_A_SPITFIRE",
    HERO_ABILITY_SKAARF_B_GOOP = "HERO_ABILITY_SKAARF_B_GOOP",
    HERO_ABILITY_SKAARF_C_DRAGON_BREATH = "HERO_ABILITY_SKAARF_C_DRAGON_BREATH",
    HERO_ABILITY_SKYE_A_NAME = "HERO_ABILITY_SKYE_A_NAME",
    HERO_ABILITY_SKYE_B_NAME = "HERO_ABILITY_SKYE_B_NAME",
    HERO_ABILITY_SKYE_C_NAME = "HERO_ABILITY_SKYE_C_NAME",
    HERO_ABILITY_VOX_A_NAME = "HERO_ABILITY_VOX_A_NAME",
    HERO_ABILITY_VOX_B_NAME = "HERO_ABILITY_VOX_B_NAME",
    HERO_ABILITY_VOX_C_NAME = "HERO_ABILITY_VOX_C_NAME",
    HalcyonChargers = "Halcyon Chargers",
    HalcyonPotion = "Halcyon Potion",
    JourneyBoots = "Journey Boots",
    MinionCandy = "Minion Candy",
    NullwaveGauntlet = "Nullwave Gauntlet",
    ProtectorContract = "Protector Contract",
    DragonbloodContract = "Dragonblood Contract",
    ReflexBlock = "Reflex Block",
    ScoutTrap = "Scout Trap",
    Shank = "Shank",
    Shiversteel = "Shiversteel",
    SprintBoots = "Sprint Boots",
    TravelBoots = "Travel Boots",
    WarTreads = "War Treads",
    WeaponInfusion = "Weapon Infusion",
    Withdraw = "Withdraw"
    
    init(string: String) {
        if let ability = AbilityType(rawValue: string) {
            self = ability
        } else {
            print("ability missing: \(string)")
            if !abilityList.contains(string) {
                abilityList.insert(string)
            }
            self = .Unset
        }
    }
}
